services:
  epg:
    container_name: epg
    image: ghcr.io/iptv-org/epg:master
    restart: unless-stopped
    ports:
      - 8410:3000
    environment:
      - TZ=Europe/Berlin
      - DAYS=2
    volumes:
      - /mnt/S24/main/configs/IPTV/epg-channels.xml:/epg/channels.xml
