services:
  ersatztv:
    container_name: ersatztv
    image: ghcr.io/ersatztv/ersatztv
    restart: unless-stopped
    ports:
      - 8409:8409
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/.ix-apps/app_mounts/ersatztv/config:/config
      - /mnt/S24/main/media:/media:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
